<template>
  <div>
    <PageLoader :show="true" :time="800" />
    <Header />
    <div class="disclaimer bg-lightgrey padding-top-100 padding-bottom-40">
      <div class="container">
        <div class="row">
          <div class="col-12 mb-4 mb-md-5">
            <h3>Cryptbids Privacy Policy</h3>
            <p>Last revised: 10 November, 2020</p>
          </div>
          <div class="col-12 mb-4 mb-md-5">
            <h3>Welcome to Cryptbids!</h3>
            <p>
              Cryptbids values your privacy. This notice describes what
              information we collect, how we use it, and, if necessary, those
              with whom we share it. <br /><br />
              By visiting Cryptbids, you are accepting the practices described
              in this Privacy Policy. Your use of the Website is also subject to
              our Terms and Conditions.
              <br /><br />
              Our Privacy Policy is written according to the CalOPPA (California
              Online Privacy Protection Act) and the GDPR (General Data
              Protection Regulation – European regulation).
            </p>
          </div>
          <div class="col-12 mb-4 mb-md-5">
            <h3>General Information</h3>
            <p>
              The personal data of the users that are collected and processed
              through the website: <br /><br />
              Will be under responsibility and in charge of:
              <br /><br />
              Cryptbids info@cryptbids.com (Hereinafter referred to as
              “Cryptbids”)
              <br /><br />
              Types of Information gathered
              <br /><br />
              The information we learn from customers helps personalize and
              continually improve your experience at Cryptbids. Here are the
              types of information we gather:
              <br /><br />
              Information You Give Us. You provide information when you search,
              read and watch the content, open an account, buy and exchange
              cryptocurrencies or communicate with us. As a result of those
              actions, you might supply us with the following information:
              <br /><br />
              First and last name.
              <br /><br />
              Username.
              <br /><br />
              Email address.
              <br /><br />
              IP address
              <br /><br />
              Payment information.
              <br /><br />
              Social media profile information.
              <br /><br />
              Any additional information relating to you that you provide to us
              directly through our websites or indirectly through our websites
              or online presence such as ‘cookies’. Cryptbids will not collect
              any personally identifiable information about you, unless you
              provide it.
              <span class="text-heavy">Payment information:</span> Your payment
              information, will be processed by Bitcoin Ethereum and Litecoin,
              which will treat and safeguard your data with total security and
              with the exclusive purpose of processing the purchase of the
              Cryptocurrencies. Cryptbids reserves the right to contract any
              payment platform available in the market, which treats your data
              for the exclusive purpose of processing the purchase and exchanges
              of the Cryptocurrencies. <br /><br />
              Google Analytics: We use Google Analytics provided by Google,
              Inc., USA (“Google”). These tool and technologies collect and
              analyze certain types of information, including IP addresses,
              device and software identifiers, referring and exit URLs, feature
              use metrics and statistics, usage and purchase history, media
              access control address (MAC Address), mobile unique device
              identifiers, and other similar information via the use of cookies.
              The information generated by Google Analytics (including your IP
              address) may be transmitted to and stored by Google on servers in
              the United States. We use the GOOGLE Analytics collection of data
              to enhance the website and platform and improve our service.
            </p>
            <p>
              Automatic Information: Like many websites, we use “cookies.” We
              obtain certain types of anonymous information which is not
              personally identifiable when your web browser accesses Cryptbids
              or third-party content served by or on behalf of Cryptbids on
              other websites. Some of the information we collect and analyze
              includes the Internet protocol (IP) address; computer and
              connection information such as browser type, version, and
              connection speed; purchase history; and the content you searched
              for, viewed, and possibly purchased. <br /><br />
              How Long We Keep Your Data
              <br /><br />
              Personal data will be kept for the time necessary for the
              provision of the services or as long as the interested party does
              not withdraw their consent.
              <br /><br />
              How We Use Your Information
              <br /><br />
              In general, we use the information we collect primarily to
              provide, maintain, protect and improve our current website,
              platform and services and to develop new services. We use personal
              information collected through our site as described below and
              described elsewhere in this Policy to:
              <br /><br />
              Identify you as a user in our system. Provide access and use of
              the platform. Create and manage user accounts. Process
              transactions and payments of cryptocurrencies. Improve our
              platform, services, website, and how we operate our business.
              Understand and enhance your experience using our website and
              services. Send emails through bulk email delivery platforms such
              as MailChimp and Klaviyo. Respond to your comments or questions
              and for our support team to provide service. Send you related
              information, including confirmations, invoices, technical notices,
              updates, security alerts and support and administrative messages.
              Communicate with you about upcoming events and news about products
              and services offered by Cryptbids and our selected partners.
              Marketing purposes of Cryptbids (Google ads, Facebook ads, twitter
              ads, Pinterest ads, Instagram ads, etc). Link or combine your
              information with other information we get from third parties to
              help understand your needs and provide you with better service.
              Protect, investigate and deter against fraudulent, unauthorized or
              illegal activity. How Do You Get My Consent ?

              <br /><br />
              By making use of our platform and services and provide us with
              personal information to communicate with you, you agree that we
              collect and use your information. You can withdraw your consent,
              contact us through the contact information or the support page.
              <br /><br />
              Social Networks
              <br /><br />
              On our website you will find links and functions linked to
              different social networks, in which you can share your
              information.
              <br /><br />
              It is advisable to consult the privacy policy and data protection
              of each social network used on our website.
              <br /><br />
              Facebook: https://www.facebook.com/privacy/explanation Twitter:
              https://twitter.com/privacy Instagram:
              http://instagram.com/about/legal/privacy YouTube:
              https://www.youtube.com/yt/about/de
              <br /><br />
              Cookies
              <br /><br />
              When you visit Cryptbids website, we send one or more cookies.
              <br /><br />
              What are cookies ?
              <br /><br />
              “Cookies” are small text files that are stored on your computer or
              mobile device when you visit a website. They allow the website to
              recognize your device and remember if you have been to the website
              before.
              <br /><br />
              Cookies are very common web technology; most websites use Cookies
              and have done for years. Cookies are widely used in order to make
              websites work more efficiently, as well as providing information
              to the owners of websites.
              <br /><br />
              Cookies are used to measure which parts of the website people
              visit and to customize your experience. Cookies also provide
              information that helps us monito and improve the website’s
              performance.
              <br /><br />
              Refusing or withdrawing consent to the use of cookies
              <br /><br />
              If you do not want Cookies to be dropped on your device, you can
              adjust the setting of your Internet browser to reject the setting
              of all or some Cookies and to alert you when a Cookie is placed on
              your device. For further information about how to do so, please
              refer to your browser ‘help’, ‘tool’, or ‘edit’ section. Please
              note that if you use your browser settings to block all Cookies,
              including strictly necessary Cookies (see below), you may not be
              able to access or use all or parts of the functionalities of the
              Cryptbids website.
              <br /><br />
              We provide the links for the management and blocking of cookies
              depending on the browser you use:
              <br /><br />
              Internet Explorer:
              http://windows.microsoft.com/es-xl/internet-explorer/delete-manage-cookies#ie=ie-10
              Firefox:
              http://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-que-los-sitios-we
              Chrome: https://support.google.com/chrome/answer/95647?hl=en
              Safari: https://www.apple.com/legal/privacy/es/cookies You can
              also delete the cookies you have saved in your browser by going to
              its configuration options.
              <br /><br />
              Our Cookies are used for the following purposes:
              <br /><br />
              Strictly Necessary: These Cookies are essential for Cryptbids
              website and platform to perform its basic functions.
              <br /><br />
              Functionality: These Cookies are used to store preferences set by
              users such as account name, language, and location. This allows
              Cryptbids websites to provide you with personalized features.
              <br /><br />
              Security: We use these Cookies to help identify and prevent
              potential security risks.
              <br /><br />
              Analytics and Performance: Performance Cookies collect information
              on how users interact with our websites, including what pages are
              visited most, as well as other analytical data. We use these
              details to improve how our websites function and to understand how
              users interact with them.
              <br /><br />
              Advertising (Facebook ADS, Google ADS, YouTube ADS, Twitter ADS,
              etc): These Cookies are used to display relevant advertising to
              visitors who use our services or visit websites we host or
              provide, as well as to understand and report on the efficacy of
              ads served on our websites. They track details such as the number
              of unique visitors, the number of times particular ads have been
              displayed, and the number of clicks the ads have received. They
              are also used to build user profiles, including showing you ads
              based on products you’ve viewed on our websites. These are set by
              Cryptbids and trusted third party networks and are generally
              persistent in nature.
              <br /><br />
              How We Share Information
              <br /><br />
              Information about our customers is an important part of our
              business, and we are not in the business of selling it to others.
              We share customer information only as described below.
              <br /><br />
              Third-Party Service Providers: We employ other companies and
              individuals to perform functions on our behalf. Examples include
              process transactions and payments (Bitcoin Ethereum and Litecoin),
              sending email, analyzing data, providing marketing assistance,
              providing search results and links. They have access to personal
              information needed to perform their functions, but may not use it
              for other purposes.
              <br /><br />
              Business Transfers : In the event that Cryptbids creates, merges
              with, or is acquired by another entity, your information will most
              likely be transferred. Cryptbids will email you or place a
              prominent notice on our Website before your information becomes
              subject to another privacy policy.
              <br /><br />
              Protection of Cryptbids and others : We release personal
              information when we believe release is appropriate to comply with
              the law, enforce or apply our Terms and conditions and other
              agreements, or protect the rights, property, or safety of
              Cryptbids, our users or others. This includes exchanging
              information with other companies and organizations for fraud
              protection and credit risk reduction.
              <br /><br />
              With Your Consent : Other than as set out above, you will receive
              notice when personally identifiable information about you might go
              to third parties, and you will have an opportunity to choose not
              to share the information.
              <br /><br />
              Anonymous Information : Cryptbids uses the anonymous browsing
              information collected automatically by our servers primarily to
              help us administer and improve the platform and website. We may
              also use aggregated anonymous information to provide information
              about the website to potential business partners and other
              unaffiliated entities. This information is not personally
              identifiable.
              <br /><br />
              Email Address : The email address that you supply to us for
              purposes of receiving our email communications will never be
              rented or sold to a third party.
              <br /><br />
              Protecting Your Information
              <br /><br />
              We work to protect the security of your information during
              transmission by using Secure Sockets Layer (SSL) software, which
              encrypts information you input. If transactions are processed on
              the Website, transaction information is transmitted to and from
              the Website in encrypted form using industry-standard SSL
              connections to help protect such information from interception. We
              restrict authorized access to your personal information to those
              persons who have a legitimate purpose to know that information to
              provide products or services to you and those persons you have
              authorized to have access to such information. Cryptbids follows
              generally accepted industry standards to protect the personal
              information submitted to us, both during transmission and once
              Cryptbids receives it. No method of transmission over the
              Internet, or method of electronic storage, is 100% secure.
              Therefore, while Cryptbids strives to use commercially acceptable
              means to protect your personal information, we cannot guarantee
              its absolute security.
              <br /><br />
              We will not sell, distribute, or lease your personal information
              to third parties unless we have your permission or are required by
              law to do so.
              <br /><br />
              YOUR RIGHTS
              <br /><br />
              You have the following rights in relation to your personal data
              provided to Cryptbids:
              <br /><br />
              Access your personal data. Request the correction of inaccurate
              data. Request its deletion. Request limitation of the processing
              of your data. Oppose the treatment of your data. Request your
              portability. Not be subject to automated individual decisions. The
              Users can exercise all these rights contacting us through the
              contact information or the contact page and indicating the reason
              for his request.
              <br /><br />
              Without preconception to any other administrative appeal or legal
              action, the User shall have the right to submit a claim to a
              Control Authority, in particular in the Member State in which he
              or she has their habitual residence, place of work or place of the
              alleged infringement, in If you consider that the processing of
              your personal data is not appropriate to the regulations, as well
              as in the case of not seeing the exercise of your rights
              satisfied. The control authority in which the claim was filed will
              inform the claimant about the course and result of the claim.
              <br /><br />
              EU Members Rights (GDPR Compliant)
              <br /><br />
              If you are habitually located in the European Union, you have the
              right to access, rectify, download or erase your information, as
              well as the right to restrict and object to certain processing of
              your information. While some of these rights apply generally,
              certain rights apply only in certain limited circumstances.
              <br /><br />
              We describe these rights below:
              <br /><br />
              Access and Porting: You can access of your information by contact
              us.
              <br /><br />
              Rectify, Restrict, Limit, Delete: You can also rectify, restrict,
              limit or delete much of your information by contacting us.
              <br /><br />
              Object: Where we process your information based on our legitimate
              interests explained above, or in the public interest, you can
              object to this processing in certain circumstances. In such cases,
              we will cease processing your information unless we have
              compelling legitimate grounds to continue processing or where it
              is needed for legal reasons.
              <br /><br />
              Revoke consent: Where you have previously provided your consent,
              such as to permit us to process health-related data about you, you
              have the right to withdraw your consent to the processing of your
              information at any time. For example, you can withdraw your
              consent by updating your settings. In certain cases, we may
              continue to process your information after you have withdrawn
              consent if we have a legal basis to do so or if your withdrawal of
              consent was limited to certain processing activities.
              <br /><br />
              Complain: Should you wish to raise a concern about our use of your
              information (and without prejudice to any other rights you may
              have), you have the right to do so with your local supervisory
              authority.
              <br /><br />
              Additionally, if you are a European resident, we note that we are
              processing your information in order to fulfil contracts we might
              have with you or otherwise to pursue our legitimate business
              interests listed above. Additionally, please note that your
              information will be transferred outside of Europe.
              <br /><br />
              California Online Privacy Protection Act Compliance (CalOPPA)
              <br /><br />
              Because we value your privacy, we have taken the necessary
              precautions to be in compliance with the California Online Privacy
              Protection Act (CalOPPA). According to the California Online
              Privacy act, you have the following rights:
              <br /><br />
              Know what personal data is being collected. Know whether your
              personal data is sold or disclosed and to whom. Access to your
              personal data. Request to delete any personal information about
              you. Not be discriminated against for exercising their privacy
              rights. Children’s Online Privacy Protection
              <br /><br />
              We are in compliance with the requirements of the GDPR (General
              Data Protection Regulation), and the California Online Privacy
              Protection Act (CalOPPA) regarding the protection of the personal
              data of minors. We do not collect any information from anyone
              under 13 years of age. Our website, platform and services are all
              directed to people who are at least 18 years old or older.
              <br /><br />
              Editing and Deleting Information
              <br /><br />
              If you believe that any information, we are holding on you is
              incorrect or incomplete, please write to or email us as soon as
              possible. We will promptly correct any information found to be
              incorrect. You can change, modify, rectify and delete your
              Information at any time, please contact us through the contact
              information.
              <br /><br />
              To opt-out of Cryptbids email, follow the instructions included in
              the email. Your request should be processed within 48 hours.
              <br /><br />
              Suppliers and Other Third Parties
              <br /><br />
              Except as otherwise expressly included in this Privacy Policy,
              this document addresses only the use and disclosure of information
              Cryptbids collects from you. If you disclose your information to
              others, whether other users or suppliers on Cryptbids, different
              rules may apply to their use or disclosure of the information you
              disclose to them. Cryptbids does not control the privacy policies
              of third parties, and you are subject to the privacy policies of
              those third parties where applicable. Cryptbids is not responsible
              for the privacy or security practices of other websites on the
              Internet, even those linked to or from the Cryptbids site.
              Cryptbids encourages you to ask questions before you disclose your
              personal information to others.
              <br /><br />
              Changes To This Privacy Policy
              <br /><br />
              Cryptbids will post modifications by date to this Privacy Policy
              to inform you of any changes. Cryptbids reserves the right to
              modify this Privacy Policy at any time, please review it
              frequently.
              <br /><br />
              Enforcement
              <br /><br />
              Cryptbids regularly reviews its compliance with this Policy.
              Please feel free to direct any questions or concerns regarding
              this Policy or Cryptbids treatment of personal information by
              contacting us.
              <br /><br />
              When we receive formal written complaints, it is Cryptbids policy
              to contact the complaining user regarding his or her concerns. We
              will cooperate with the appropriate regulatory authorities,
              including local data protection authorities, to resolve any
              complaints regarding the transfer of personal data that cannot be
              resolved between Cryptbids and an individual.
              <br /><br />
              Contact Us
              <br /><br />
              If you have questions or concerns about these Privacy Policy and
              the handling and security of your data on this site, please
              contact us throw our contact page or contact at:
              <br /><br />
              info@cryptbids.com
            </p>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>
</template>

<script>
import { InertiaLink } from "@inertiajs/inertia-vue";
import Header from "./../Header/Header";
import Footer from "./../Footer/Footer";
import PageLoader from "./../PageLoader/PageLoader";
export default {
  components: {
    InertiaLink,
    Header,
    Footer,
    PageLoader,
  },
};
</script>

<style>
</style>